"""empty message

Revision ID: 460f0237203e
Revises: 74a4d0a7d006
Create Date: 2021-06-17 10:10:20.592848

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '460f0237203e'
down_revision = '74a4d0a7d006'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticket', sa.Column('userId', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'ticket', 'users', ['userId'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ticket', type_='foreignkey')
    op.drop_column('ticket', 'userId')
    # ### end Alembic commands ###
