"""empty message

Revision ID: 6d8037d78b23
Revises: 
Create Date: 2021-06-17 09:16:24.290335

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d8037d78b23'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bus',
    sa.Column('busId', sa.Integer(), nullable=False),
    sa.Column('busName', sa.String(), nullable=False),
    sa.Column('startingPoint', sa.String(), nullable=False),
    sa.Column('endingPoint', sa.String(), nullable=False),
    sa.Column('totalSeats', sa.String(), nullable=False),
    sa.Column('cost', sa.Integer(), nullable=False),
    sa.Column('busType', sa.String(), nullable=False),
    sa.Column('availDate', sa.DateTime(), nullable=True),
    sa.Column('availSeat', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('busId')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('contact', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ticket',
    sa.Column('tickeId', sa.Integer(), nullable=False),
    sa.Column('bookingDate', sa.DateTime(), nullable=False),
    sa.Column('seats', sa.Integer(), nullable=False),
    sa.Column('busId', sa.Integer(), nullable=True),
    sa.Column('travelDate', sa.DateTime(), nullable=True),
    sa.Column('userId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['busId'], ['bus.busId'], ),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('tickeId')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ticket')
    op.drop_table('users')
    op.drop_table('bus')
    # ### end Alembic commands ###
