"""empty message

Revision ID: 74a4d0a7d006
Revises: 6d8037d78b23
Create Date: 2021-06-17 09:58:30.715218

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74a4d0a7d006'
down_revision = '6d8037d78b23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ticket_userId_fkey', 'ticket', type_='foreignkey')
    op.drop_column('ticket', 'userId')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticket', sa.Column('userId', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('ticket_userId_fkey', 'ticket', 'users', ['userId'], ['id'])
    # ### end Alembic commands ###
